feat(auth): #Y-16 Реализовать логику авторизации
AVor0n/tank-chess pull request #14
Opened 2023-12-20 02:26 UTC by k-vyaznikova

Реализована логика авторизации и регистрации.
Если пользователь не авторизован, то он перенаправляется на страницу логина. 
В случае успешной авторизации или регистрации пользователь перенаправляется на страницу, с которой пришел, либо на главную.

2023-12-20 09:17 UTC, Filin1985 requested changes
Лучше стянуть текущие изменения из ветки main. В текущем варианте есть конфликты. Также добавились определенные правила по неймингу. Например ты не сможешь сделать commit если наименование стилей написаны в camelCase.

2023-12-23 05:58 UTC, Filin1985 requested changes

2023-12-23 05:58 UTC, Filin1985 commented on packages/client/src/pages/authPage/signIn/signIn.tsx
> +      <div
Не очень понятен функционал кнопки "Выйти" в данном месте. Мы ее сразу видим на форме авторизации. Ее наверно нужно добавить в профиль, а то получается в данный момент разлогиниться пользователь не сможет

2023-12-23 05:58 UTC, Filin1985 commented on packages/client/src/pages/authPage/signUp/signUp.tsx
>        </Button>
Ниже есть ссылка "Авторизация". Нужна ли она здесь? Мы же можем туда по табам сверху переходить

2023-12-23 05:58 UTC, Filin1985 commented on packages/client/src/service/auth.service.ts
> +    fetch(this.baseURL + '/auth/signin', {
Может везде использовать async/await? Сейчас два запроса написаны с fetch, а другие два с async/await

2023-12-23 05:58 UTC, Filin1985 commented on packages/client/src/pages/authPage/signIn/signIn.tsx
>      <form className={styles.form}>
У нас есть компонент Form, мы можем его в данном случае использовать? Он вроде даже с валидацией полей

2023-12-23 05:58 UTC, Filin1985 commented on packages/client/src/types/types.ts
> +export interface signUpDataType {
Может все типы будем с заглавной буквы именовать?

2023-12-23 05:58 UTC, Filin1985 commented on packages/client/src/pages/authPage/signUp/signUp.tsx
> +  const submit = (data: signUpDataType, changeAuth: (statement: boolean) => void) => {
Может здесь брать данные из замыкания? Мне кажется так проще понять 
`const submit = () => {
    AuthService.signUp(signUpData, () => {
      setAuth(true)
      navigate(from, { replace: true })
    })
  }`

А внизу в onClick просто передавать submit

2023-12-23 10:23 UTC, k-vyaznikova commented on packages/client/src/pages/authPage/signIn/signIn.tsx
> +      <div
нет, это я забыла ее удалить)) логаут тестировала

2023-12-23 20:39 UTC, vakulovv commented on packages/client/src/app.tsx
> +        setLoading(true)
наверно setLoading надо выставить в true до того, как рарезолвятся данные

2023-12-23 21:26 UTC, vakulovv commented on packages/client/src/context/userContext.tsx
я бы объединил контексты в один authContext

2023-12-24 14:57 UTC, k-vyaznikova commented on packages/client/src/app.tsx
> +        setLoading(true)
тут вроде все верно

2023-12-24 15:06 UTC, k-vyaznikova commented on packages/client/src/pages/authPage/signUp/signUp.tsx
>        </Button>
убрала, хотя, конечно, это привычное ссылки на возврат к авторизации.

2023-12-24 15:07 UTC, k-vyaznikova commented on packages/client/src/pages/authPage/signIn/signIn.tsx
>      <form className={styles.form}>
настроила.

2023-12-24 15:07 UTC, k-vyaznikova commented on packages/client/src/types/types.ts
> +export interface signUpDataType {
да, с большой будет консистентнее

2023-12-24 15:08 UTC, k-vyaznikova commented on packages/client/src/pages/authPage/signUp/signUp.tsx
> +  const submit = (data: signUpDataType, changeAuth: (statement: boolean) => void) => {
переделала этот участок кода, так как добавила валидацию.

2023-12-24 15:08 UTC, k-vyaznikova commented on packages/client/src/context/userContext.tsx
обсудили ранее, что тут будут переделки в 6ом спринте

2023-12-24 16:29 UTC, Filin1985 submitted a review, later dismissed

2023-12-25 07:36 UTC, AVor0n commented on packages/client/src/app.tsx
> +        setLoading(true)
Да, с точки зрения логики работы всё верно, просто именование немного путаницу вызывает.
Обычно `loading` значит, что `идет процесс загрузки`. Т.е. изначально ставится в `true`, а как данные подгрузятся ставится в `false`.
Тут значения инвертированы сначала `false`, а потом `true`. И на мой взгляд понятнее было бы если переменная называлась `loaded`, т.е. хранила значение, что `данные загружены`.

2023-12-25 10:27 UTC, IvanPeleshok requested changes
Добрый день, Кристина!

Проделана большая работа!
Отлично потрудились!

Есть два критических замечания связанных с отсутствием массива зависимостей для useEffect и значением для переменной loading

Все остальные замечания являются рекомендацией

Предлагаю доработать

Хорошего дня :)

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/app.tsx
> +        if (user && user?.id > 0) setAuth(true)
user?.id (в данном случае проверка `user &&` избыточна)

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/app.tsx
> +      .then(user => {
Предлагаю использовать async / await + try / catch для работы с промисами для лучшей читаемости кода

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/app.tsx
> +  return loading ? (
Полагаю, что когда происходит загрузка - должен отображаться ui загрузки
Немного путает, предлагаю перенести значения для переменной с false на true

```
if (isLoading) {
 return <PageLoader />
}

return (
  <React.StrictMode>
  ...
 )

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/app.tsx
> +  })
Погалагаю, что загружка должно произойти единожды, а для этого необходимо использовать пустой массив зависимостей для useEffect вторым аргументом (если не так, то необходимо задать список зависимостей, иначе хук будет вызываться на каждый ререндер)
https://legacy.reactjs.org/docs/hooks-effect.html

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/pages/authPage/authPage.tsx
> +    AuthService.signIn(data as unknown as SignInDataType, () => {
Кастить не очень хорошо, лучше сразу передавать значения с нужным интерфейсом
В чём возникли проблемы с типизацией?

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/service/auth.service.ts
> +      const response: Response = await fetch(this.baseURL + '/auth/signup', {
Предлагаю обратить внимание на библиотеку `axios`
Отпадёт необходимость на проверку статусов ответа, есть возмжность прокидывать типы ответа и т.д
Есть возможность сконфигурировать базовый конфиг, чтобы не было необходимости в конфигурации для каждого запроса: https://axios-http.com/ru/docs/instance

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/service/auth.service.ts
> +      if ((result as User).id > 0) afterSignUp(data.login, data.password)
if предлагаю писать с писать с помощью блока c указанием `{ }`
Читаемость в таком случае намного лучше

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/pages/authPage/authPage.tsx
> +    if (isAuth) navigate(from, { replace: true }) //
// можно удалить

2023-12-25 10:27 UTC, IvanPeleshok commented on packages/client/src/service/auth.service.ts
> +const authServ = new AuthService()
Предлагаю не сокращать названия переменных
```
const authService = new AuthService()

2023-12-25 12:14 UTC, Filin1985 approved these changes

2023-12-25 13:51 UTC, IvanPeleshok requested changes
Предлагаю поправить одно критическое замечание, которое не заметил при первой итерации проверки

2023-12-25 13:51 UTC, IvanPeleshok commented on packages/client/src/pages/authPage/authPage.tsx
> +  })
Не хватает массива зависимостей

2023-12-26 16:59 UTC, IvanPeleshok approved these changes
Работа не имеет критических замечаний!
Апрув

Хорошего дня :)

2023-12-26 17:33 UTC, Filin1985 approved these changes

2023-12-26 17:50 UTC, merged