Y 33
AVor0n/tank-chess pull request #19
Opened 2023-12-31 07:01 UTC by k-vyaznikova

- Настроено хранение данных пользователя redux  с исп библиотеки redux-toolkit
- Добавлен слайд для user
- В компоненте Avatar исправлен баг с загрузкой аватара
- Исправлено отображение Аватара, если картинка большая
- На странице профиля добавлена кнопка «выйти"

2023-12-31 14:29 UTC, AVor0n reviewed
gitignore бы поправить, чтоб log не пушился.
насчет createApi - я бы попробовал его применить,. т.к. кажется что с ним будет красивше и удобнее, но возможно с ним какие-то проблемы будут.
 
 Про редакс скорее Марат знает как лучше делать, т.к. насколько помню работает с redux

2023-12-31 14:29 UTC, AVor0n commented on packages/client/src/service/auth.service.ts
> +  async logout(callback: () => void) {
Можно кстати переделать сервисы на использование createApi из [redux toolkit queries](https://redux-toolkit.js.org/rtk-query/overview#basic-usage)
Я правда сам не использовал это ни разу, т.к. не работал с redux, но выглядит как более удобный способ работы с api, когда есть redux. Т.к. потом для запросов можно будет использовать получившиеся хуки и не надо будет самостоятельно прописывать pending/error состояния и их переключение, т.к. это будет браться из хука

2024-01-02 06:03 UTC, Filin1985 requested changes

2024-01-02 06:03 UTC, Filin1985 commented on packages/client/src/pages/authPage/authPage.tsx
> +  const submitLogin = async (data: Record<string, string | File>) => {
Запросы к api с redux делают с помощью thunk (https://redux-toolkit.js.org/api/createAsyncThunk).
Вот пример 
`const registerUser = createAsyncThunk(
  "registration/register",
  async (
    { firstName, lastName, email, password}: TUserRegister,
    { dispatch, rejectWithValue }
  ) => {
    try {
      const response = registerUserRequestApi({
        firstName,
        lastName,
        email,
        password,
      })
      dispatch(setUserData(response))
    } catch (error) {
      return rejectWithValue(error)
    }
  }
)`
Потом этот запрос мы используем в createSlice, таким образом:
`export const registerSlice = createSlice({
  name: "registration",
  initialState,
  reducers: {},
  extraReducers(builder) {
    builder.addCase(registerUser.pending, (state) => {
      state.registerRequest = true
      state.registerSuccess = false
      state.registerFailed = false
    })
    builder.addCase(registerUser.fulfilled, (state) => {
      state.registerRequest = false
      state.registerSuccess = true
      state.registerFailed = false
    })
    builder.addCase(registerUser.rejected, (state) => {
      state.registerRequest = false
      state.registerSuccess = false
      state.registerFailed = true
    })
  },
})`

Сам запрос можно расположить в файле со слайсом, а можно отдельно в папку thunks конкретного редюсера.
Также есть еще createEntityAdapter, с ним проще делать CRUD операции

2024-01-02 19:36 UTC, k-vyaznikova commented on packages/client/src/pages/authPage/authPage.tsx
> +  const submitLogin = async (data: Record<string, string | File>) => {
Марат, кажется, что редьюсеры - это чистые функции, если можно в них избежать асинхронности - говорят, лучше избежать. Я бы все же разделила апи и редьюсеры. как ты считаешь?

2024-01-03 08:51 UTC, Filin1985 approved these changes

2024-01-04 08:26 UTC, DazzlingFame approved these changes
Привет! Отличная работа, критичных замечаний нет, реквест принимаю! Оставил несколько пожеланий в коде, обрати внимание.

2024-01-04 08:27 UTC, DazzlingFame commented on packages/client/src/app.tsx
> +    fetchUser()
Увидел такое и дальше в других файлах

2024-01-04 20:02 UTC, Filin1985 approved these changes

2024-01-05 03:06 UTC, merged