feat(main page): #Y-12 Сверстать главную страницу игры: меню
AVor0n/tank-chess pull request #2
Opened 2023-12-09 10:17 UTC by Filin1985

Сверстать главную страницу игры с основным меню

![Screenshot 2023-12-09 at 13 04 52](https://github.com/AVor0n/tank-chess/assets/16574140/a5195d09-e6f1-4c3b-b54b-0882d5047e5a)

2023-12-09 11:34 UTC, Denis-Ostapenko requested changes

2023-12-09 11:34 UTC, Denis-Ostapenko commented on packages/client/src/components/menu/Menu.tsx
Для того чтобы компонент Menu сделать переиспользуемым, нужно заголовок и линки получать из props.
Одно из решений в файле MainPage компоненту Menu передать заголовок и массив линков [{ label: 'Начать игру', to: '/game'}, ...]

2023-12-09 11:44 UTC, AVor0n reviewed
Кажется надо ещё ограничение по высоте для картинки добавить, т.к. у меня с экроном 1920x1080 появляется вертикальный скрол. Если `max-height: 100vh` на картинку повесить, все норм становится

Ну и `src/assetes/.keep` можно удалить, т.к. в этой директирии теперь есть фаайлы и смысла в этом файле нет

2023-12-09 11:44 UTC, AVor0n commented on packages/client/src/components/menu/Menu.tsx
> +import styles from './menu.module.css'
Классно, что css-modules добавил, тоже хотел их предложить.

2023-12-09 11:44 UTC, AVor0n commented on packages/client/src/pages/mainPage/MainPage.tsx
> +import { Menu } from '../../components/menu/Menu'
Есть предложение использовать `index.ts` файлы. Тогда количество строк с импортом можно сократить.
Вместо 
```js
import { Menu } from '../../components/menu/Menu'
import { Link } from '../../components/link/Link'
import { Button } from '../../components/button/Button'
```
будет
```js
import { Menu, Link, Button } from '../../components'
```
Плюс это создание public api для модулей, что позволяет делать меньше движений при рефакторе
Из миинусов надо создавать доп файлы, но это дегко делается с помощью расширений типа [TypeScript Barrel Generator](https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-typescript-exportallmodules)

[статейка про index.ts](https://habr.com/ru/companies/nlmk/articles/704386/)

2023-12-09 11:48 UTC, AVor0n commented on packages/client/src/components/menu/Menu.tsx
У меня тут кстати наоборот возникла мысль 'зачем отдельный компонент `menu`?'.
Я бы просто заинлайнил его в `MainPage`. Т.к. этот компонент занимает половину страницы и на других страницах навигацию удобнее было бы через header со ссылками делать, чтоб больше места основному контенту было

2023-12-10 07:05 UTC, AVor0n commented on packages/client/src/components/menu/menu.module.scss
> +  .subtitle {
Тут кстати не обязательна вложенность, за счет модулей стили и так не будут не будут конфликтовать с другими.
Так что из вложенности я бы только `&:hover` оставил, т.к. он позволяет не дублировать название класса

2023-12-10 07:12 UTC, AVor0n approved these changes

2023-12-10 07:17 UTC, Denis-Ostapenko approved these changes

2023-12-10 07:22 UTC, merged