feat(emoji): Y-44-45 Эмодзи - клиентская и серверная части
AVor0n/tank-chess pull request #42
Opened 2024-02-10 15:54 UTC by k-vyaznikova

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-02-10 16:39 UTC, Filin1985 approved these changes

2024-02-10 17:18 UTC, Olegas commented on packages/client/src/service/reaction.service.ts
> +      const response: Response = await fetch(this.baseURL + '/reactions/add', {
А здесь точно /add? В описании был адрес /import

2024-02-10 17:19 UTC, Olegas commented on packages/client/src/service/reaction.service.ts
> +        return { code, id, quantity, emojiId }
А зачем разбирать на значения а потом снова собирать новый объект с теми же полями? Это как минимум создание лишнего объекта.

2024-02-10 17:29 UTC, Olegas requested changes
Добрый день.
В реализации есть проблемы. Написал подробно в чем именно в комментариях к коду. Надо исправить

2024-02-10 17:29 UTC, Olegas commented on packages/server/controllers/reaction.ts
> +    }
Так делать не правильно. Если придут два запроса, каждый их них попытается найти запись, не найдет, пойдет создавать новую - в базе будет дубль. Нужно использовать конструкцию типа ON CONFLICT DO UPDATE + на таблице должен быть уникальный индекс что бы на уровне БД предотвратить создание дублей

2024-02-10 17:29 UTC, Olegas commented on packages/server/controllers/reaction.ts
> +    }
Здесь та же проблема. Два запроса, оба нашли реакцию с quantity = 1, оба пошли делать decrement, в итоге получили -1. Здесь бы нужна блокировка типа SELECT FOR UPDATE

2024-02-10 17:29 UTC, Olegas commented on packages/server/models/reaction.ts
> +export class Reaction extends Model<ReactionProps, CreateReactionProps> {
Судя по всему нужен уникальный индекс на пару comment_id, emoji_id для предотвращения вставки дублей. Этот же индекс будет использоваться для поиска всех эмодзи для данного комментария

2024-02-10 19:55 UTC, k-vyaznikova commented on packages/client/src/service/reaction.service.ts
> +      const response: Response = await fetch(this.baseURL + '/reactions/add', {
да, тут верно.
потом в итоге через консоль ручку для заполнения базы дергала, поэтому не заметила, что здесь не поправлено. первоначально она называлась api/reaction/add

2024-02-11 00:31 UTC, k-vyaznikova commented on packages/server/models/reaction.ts
> +export class Reaction extends Model<ReactionProps, CreateReactionProps> {
насколько я поняла из документации, если добавить двум колонкам @Unique с одинаковым названием, то получиться уникальный ключ из нескольких столбцов.  так и сделала. верно это?

2024-02-11 00:33 UTC, k-vyaznikova commented on packages/server/controllers/reaction.ts
> +    }
поправила, объединив два запроса в одну транзакцию и задав этой транзакции isolationLevel: Transaction.ISOLATION_LEVELS.REPEATABLE_READ
прокомментируйте, пожалуйста, правильность этого решения.

2024-02-11 00:42 UTC, k-vyaznikova commented on packages/client/src/service/reaction.service.ts
> +        return { code, id, quantity, emojiId }
поправила

2024-02-11 09:54 UTC, Olegas requested changes
Repeatable read не решает проблему. Написал подробно в комментарии почему

2024-02-11 09:54 UTC, Olegas commented on packages/server/models/reaction.ts
> +export class Reaction extends Model<ReactionProps, CreateReactionProps> {
Да, так верно

2024-02-11 09:54 UTC, Olegas commented on packages/server/controllers/reaction.ts
> +    }
Repeatable read тут не поможет. Repeateable read позволяет получать стабильное чтение в рамках транзакции. Но если рассмотреть кейс, когда две транзакции пришли на пустую БД, обе прочитали пустоту, обе вставили запись то тут при комите второй транзакции обнаружится нарушение уникального индекса. В этой ситуации надо применять подход on conflict do о котором писал выше.
Во второй ситуации (с декрементом) опять же не поможет - обе транзакции увидят, допустим, 2, обе сделаю декремент до 1 и выйдут успешно (в БД останется 1) или сделают 0 (зависит от того как реализован decrement в sequelize). Я бы тут запу4стил транзакцию самую простую read committed и заблокировал нужную запись (select for update), заем спокойно правил ее. Вторая транзакция будет ждать, пока первая завершится

2024-02-13 00:24 UTC, k-vyaznikova commented on packages/server/controllers/reaction.ts
> +    }
исправила.

2024-02-13 15:33 UTC, Olegas commented on packages/server/controllers/reaction.ts
> +      const reaction: Reaction | null = await findReaction(commentId, emojiId, tr)
Вот здесь все равно не так получилось.
Как правильно сделать: см. https://stackoverflow.com/questions/64823192/increment-or-decrement-value-using-sequelize-upsert
Обрати внимание - там упоминается баг в какой-то из версий, возможно надо обновить sequelize если у вас в проекте подверженная версия. Смотрите сами с командой - переделывать или нет.

2024-02-13 15:33 UTC, Olegas commented on packages/server/controllers/reaction.ts
> +      const reaction: Reaction | null = await findReaction(commentId, emojiId, tr)
Здесь все круто

2024-02-13 15:33 UTC, Olegas commented on packages/server/controllers/reaction.ts
> +      lock: transaction?.LOCK.UPDATE,
Здесь все круто

2024-02-13 15:34 UTC, Olegas approved these changes
Работа принята. 
В коде удаления реакции все еще есть проблемы, написал там как лучше сделать. Почитай, может чуть позже доработаете с командой

2024-02-13 22:17 UTC, AVor0n approved these changes

2024-02-13 22:21 UTC, merged