Поддержать API форума на клиенте
AVor0n/tank-chess pull request #46
Opened 2024-02-14 19:51 UTC by Filin1985

2024-02-15 06:39 UTC, k-vyaznikova requested changes

2024-02-15 06:39 UTC, k-vyaznikova commented on packages/client/src/reducers/forum/commentSlice.ts
> +        state.comments.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
а нельзя сделать сортировку на этапе запроса к БД?

2024-02-15 06:39 UTC, k-vyaznikova commented on packages/client/src/pages/topicPage/components/commentItem/commentItem.tsx
> +      const reactionsOnComment: ReactionType[] = await ReactionService.getReactionsOnComment(Number(comment.id))
видимо, реакции на коммент тоже стоит перенести в редакс)))
после твоего мерджа планирую делать рефакторинг:
заполнение эмодза на создание бд, и эти изменения тогда внесу тоже тогда

2024-02-15 06:43 UTC, k-vyaznikova requested changes

2024-02-15 06:43 UTC, k-vyaznikova commented on packages/client/src/reducers/forum/commentSlice.ts
> +      if (action.payload) {
вопрос чисто с образовательной целью, чтоб я понимала:
здесь же тоже перед тем, как установить состояние, должна быть миддлвара, которая берет комментарий из базы?

2024-02-16 13:47 UTC, AVor0n commented on packages/server/index.ts
> +        user: {
В этом файле надо оставить как было.
Т.к. вместо `user` в сторе `authSlice`. И свойства `loading`, нет
Redux будет ругаться на несовместимость этого стейта с конфигурацией

2024-02-17 06:52 UTC, Filin1985 commented on packages/client/src/utils/constants.ts
> +export const SELF_API_URL = `http://localhost:3002/api`
Тут исправлю, забыл

2024-02-17 06:53 UTC, Filin1985 commented on packages/client/src/reducers/forum/commentSlice.ts
> +        state.comments.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
Можно наверно), но не изучал этот вопрос)

2024-02-17 06:54 UTC, Filin1985 commented on packages/client/src/reducers/forum/commentSlice.ts
> +      if (action.payload) {
Я их сохраняю, когда вызываю thunk для получения конкретного топика по id

2024-02-17 06:54 UTC, Filin1985 commented on packages/server/index.ts
> +        user: {
Ок, верну

2024-02-17 10:56 UTC, AVor0n commented on packages/server/controllers/reaction.ts
> +  console.log('first')
Думаю это нужно было только для отладки, можно было удалить

2024-02-17 10:57 UTC, AVor0n approved these changes

2024-02-17 11:30 UTC, AVor0n approved these changes

2024-02-17 12:49 UTC, k-vyaznikova approved these changes

2024-02-17 13:03 UTC, merged