feat(auth): #Y-19 Сверстать страницу регистрации
AVor0n/tank-chess pull request #5
Opened 2023-12-11 21:41 UTC by k-vyaznikova

Сверстала страницу авторизации и регистрации  одной страницей с табами.
Страница смены пароля состоит из двух страниц - ввод email и непосредственно смена пароля. Они немного похожие, но посчитала, что не стоит их параметризовать, поэтому их две.

2023-12-12 08:22 UTC, Denis-Ostapenko requested changes

2023-12-12 08:22 UTC, Denis-Ostapenko commented on packages/client/src/pages/authPage/AuthPage.tsx
Получились слишком сложные компоненты, чтобы что-то поправить в дальнейшем придётся сначала разбираться что, где и как.
Как можно меньше используй if, где есть возможность можно использовать тернарные операторы, где-то внутри jsx кода можно тоже использовать тернарные, ото облегчит чтение кода

2023-12-12 08:22 UTC, Denis-Ostapenko commented on packages/client/src/pages/authPage/AuthPage.tsx
Но, в папке pages должны находиться компоненты с минимальной логикой и объёмом кода.
Я советую создать отдельные компоненты регистрация, авторизация, восстановление пароля и ввод почты, 

Компоненту таб достаточно просто менять номер вкладки (1 или 2) это поможет избавиться от formList.auth.id, а в компоненте AuthPage выводить в зависимости какой таб активный отдельные компоненты, который ты создашь регистрация и авторизация

2023-12-12 10:25 UTC, k-vyaznikova commented on packages/client/src/router.tsx
> Хотелось бы обойтись 1 страницей, 3 страницы это как-то много.
> 
> * у пользователя будет доступ к /password странице смена пароля, до того как он ввёл почту, это не правильно, должны быть шаги

это не может быть одна страница, так как ведь ссылку на изменение пароля обычно присылают на указанный e-mail, и она уникальная. То, что я сейчас отображаю смену пароля по /password - это временно.

2023-12-12 14:31 UTC, AVor0n commented on packages/client/src/components/form/Form.tsx
> +  }
В пропсах лучше не создавать лишнюю вложенность, это я про `btn`
Наименования лучше давать в camelCase, т.к. он в JS популярен. snake_case - в Python обычно используют.
Вместо `h2_title` лучше просто `title`. То что он он `h2` это лишние детали внутренней реализации, которые потом и изменится могут. 
Названия пропсов-обработчиков обычно называют с префиксом `on`

Т.е. на мой взгляд такой интерфейс было бы удобнее использовать
```ts
import { TextInputProps } from '@gravity-ui/uikit'

interface FormProps {
  title: string,
  description: string,
  fields: TextInputProps[],
  submitLabel?: string,
  onSubmit: () => void,
  footer: ReactNode
}
```

2023-12-12 14:31 UTC, AVor0n commented on packages/client/src/components/form/Form.tsx
> +export const Form = (props: FormProps) => {
В react для условного рендера обычно использут тернарный оператор `? :` или `&&`, а рендер массива элементов с преобразование делают через `Array.map`
Т.е. если записать вот так, то воспринималось бы проще. По крайней мере привычнее.

```tsx
export const Form: FC<FormProps> = ({ h2_title, items, btn, note, additional_nodes }) => {
  return (
    <div className={styles.form}>
      {h2_title && <h2>{h2_title}</h2>}

      {note && (
        <p key="note" className={styles.note}>
          {note}
        </p>
      )}

      {items?.map(item => (
        <div key={item.name} className={styles.inputContainer}>
          <TextInput size="xl" placeholder={item.placeholder} pin="brick-brick" type={item.type ? item.type : 'text'} />
        </div>
      ))}

      {!!items?.length && (
        <Button
          className={styles.submitBtn}
          view="action"
          width="max"
          pin="brick-brick"
          size="xl"
          onClick={() => btn?.submit_func()}>
          {btn?.label ?? 'Отправить'}
        </Button>
      )}

      <div className={styles.addLink}>{additional_nodes}</div>
    </div>
  )
}
``` 

То что все пропсы опциональные немного странно и наводит на мысль, что этот компонент пытается быть слишком универсальным. Проще сделать специалиированные компоненты под разные формы. Чем больше условий, тем меньше уверенности, что ничего не сломаешь внося правки

2023-12-15 13:05 UTC, Denis-Ostapenko approved these changes

2023-12-21 08:30 UTC, AVor0n approved these changes
Наконец-то eslint и регистрнезависимость побеждена. Это была славная битва)

2023-12-21 08:33 UTC, merged