Y-21 Сверстать экран с началом игры
AVor0n/tank-chess pull request #7
Opened 2023-12-15 12:33 UTC by Filin1985

Сверстать страницу начала игры

![Screenshot 2023-12-15 at 15 30 17](https://github.com/AVor0n/tank-chess/assets/16574140/7a5a0073-b90d-4402-8cef-a09141769888)

2023-12-15 18:19 UTC, AVor0n commented on packages/client/package.json
> +    "@gravity-ui/uikit": "^5.24.0",
Лишнее добавилось `eslint-config-prettier` и `prettier` это devDependencies, я уже перенос их туда в PR по настройке репы, так что можно просто удалить отсюда.

Ну и ставить лучше фиксированные версии зависимостей. Т.к. это более надежно. 

Можно убедиться на практике если добавить `^` в `"@types/react": "^18.2.21"`, удалить lock-файл и поставить зависимости заного. После этого в `src/main.tsx` будет ошибка о несовместимости типов, т.к. установится последняя версия `18.2.45`, а в версии `18.2.22` есть [баг](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/66841), который до сих пор не пофикшен и не совместим с `react-router`.
Если же указаны фиксированные версии пакетов, то даже без lock файла поставятся корректные зависимости. Хотя остается вероятность, что транзитивные зависимости постявят что-то плохое, т.к. их контролирет lock-файл

Для установки фиксированной версии можно использовать флаг `exact` при установке 
`yarn add something --exact`, тогда в package.json прописывается версия без крышки.
Либо можно в корне репозитория в файл `.yarnrc` дописать `save-prefix ""`, чтоб по-умолчанию ставились фиксированные версии, но с монорепой это почему то не работает. Lerna в этом плане тоже не позволяет никак фиксировать версии. Разве что обновить её до 8 версии, где управление установкой было перенесено на плечи пакетного менеджера и там вероятно заработает стандартный `.yarnrc`, но не проверял

2023-12-16 07:49 UTC, AVor0n commented on packages/client/index.html
> +    <div id="modal"></div>
Можно было ещё этот div удалить, т.к. модалка теперь в document.body рендерится

2023-12-16 07:50 UTC, Filin1985 commented on packages/client/index.html
> +    <div id="modal"></div>
Блин, точно

2023-12-16 07:52 UTC, AVor0n submitted a review, later dismissed

2023-12-16 09:46 UTC, Olegas commented on packages/client/src/components/startModal/startModal.tsx
> +  const handleUpdate: PaginationProps['onUpdate'] = (page, pageSize) => {
Для минимизации количества перерисовок здесь будет полезно использовать [useCallback](https://react.dev/reference/react/useCallback) т.к. эта функция не будет иметь зависимостей и будет всегда одна и та же (сейчас она создается новая на каждый рендер)

2023-12-16 09:47 UTC, Olegas requested changes
Добрый день.
Все здорово, но есть одно небольшое замечание, можно улучшить.
Давай доработаем.

2023-12-16 09:53 UTC, AVor0n commented on packages/client/src/components/startModal/startModal.tsx
> +  const handleUpdate: PaginationProps['onUpdate'] = (page, pageSize) => {
Компоненты в gravity-ui не обернуты же в React.Memo, по крайней мере [Modal](https://github.com/gravity-ui/uikit/blob/main/src/components/Modal/Modal.tsx)
Так что перерисовки все равно будут, даже если в `useCallback` обернуть. Есть ли смысл?

2023-12-16 11:17 UTC, Olegas commented on packages/client/src/components/startModal/startModal.tsx
> +  const handleUpdate: PaginationProps['onUpdate'] = (page, pageSize) => {
С одной стороны да, сиюминутно смысла нет. С другой стороны, твое решение не применять useCallback основано на деталях реализации библиотеки. Например завтра выйдет новая версия, где решат оптимизировать работу и применят memo. А твое приложение не получит от этого никакой пользы, потому что у тебя нет useCallback. А детали реализации, которые ты подсмотрел, изменились.

2023-12-16 13:05 UTC, Olegas approved these changes
Работа принята

2023-12-16 13:12 UTC, AVor0n approved these changes

2023-12-16 13:12 UTC, merged